name: asp.net core application build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      
      run: |
       echo "Location of current directory  $env:GITHUB_WORKSPACE and github path is $env:GITHUB_PATH"
       dir
       dotnet restore .\MicroserviceHelloWorld\MicroserviceHelloWorld.csproj
    - name: Build
      run: dotnet build .\MicroserviceHelloWorld\MicroserviceHelloWorld.csproj -c Release
    #- name: Test
     # run: dotnet test --no-build --verbosity normal
    - name: Creates directory
      run: |
         mkdir .\MicroserviceHelloWorld\PublishedOutput
    - name: Dotnet Publish
    # You may pin to the exact commit or the version.
    # uses: EasyDesk/action-dotnet-publish@75033960a28daa2ea89e0c1d8a04754568996506
      uses: EasyDesk/action-dotnet-publish@v1.0.0
      with:
        # Path to the project to publish.
        path: .\MicroserviceHelloWorld\MicroserviceHelloWorld.csproj
        # Directory where all packages will be put (default value is 'packages').
        output-dir: .\MicroserviceHelloWorld\PublishedOutput
        # Build configuration for the build (default value is 'Release').
        build-configuration: Release
        # Whether to skip the build using the --no-build flag (default value is 'true').
        skip-build: true
